export const LOREM_TEXT = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in sodales mi, ac luctus nisi. Cras porta odio odio, et facilisis tellus imperdiet eu. In tellus nulla, rhoncus ac neque non, porttitor sagittis enim. Nam euismod quis erat semper bibendum. Vivamus ac eros ac massa fringilla eleifend. Sed non erat tempus, ornare magna dapibus, fermentum mauris. Phasellus interdum nunc et nisl molestie, vel dignissim mauris facilisis. Aliquam tempor pharetra massa, ac facilisis mi pretium sed. Ut consectetur ipsum lectus, ut ultricies metus tristique nec. Praesent at eros ultricies, eleifend neque sit amet, pulvinar ante. Duis facilisis non metus sed sagittis.
Cras eget laoreet nisi, non ultricies nibh. Morbi quis rhoncus felis. Morbi condimentum aliquam odio nec auctor. Aenean nunc nisi, luctus maximus sem dapibus, ullamcorper congue eros. Integer sed urna diam. Phasellus nunc purus, auctor nec lacus sit amet, tristique dictum enim. Nam dapibus, ipsum id ultrices iaculis, lacus urna bibendum ligula, at facilisis diam tellus eget arcu. Curabitur id turpis at dolor bibendum ultrices. Duis vulputate ante est, vitae iaculis turpis porttitor vel. Pellentesque egestas mauris massa. Donec dolor eros, facilisis a vestibulum nec, eleifend ut dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum in lectus a ligula interdum euismod eget non dui. Aenean maximus elit vel odio cursus faucibus. Sed nec massa at arcu interdum molestie.
Phasellus pulvinar imperdiet nulla, in tincidunt nisl. Donec feugiat luctus nisl et pretium. Suspendisse non efficitur ligula, at ullamcorper libero. Nunc viverra non mi id consectetur. Maecenas lacinia quam justo, in eleifend dolor tempus ut. Proin porttitor justo nec scelerisque commodo. Sed in neque quis quam rhoncus suscipit ac et ex. Vestibulum urna leo, cursus at libero vitae, pellentesque consectetur nisl. In faucibus suscipit massa fermentum viverra. Maecenas id sem eu ex efficitur suscipit quis id quam. Vivamus tincidunt malesuada nunc, in euismod turpis euismod id.
Vivamus condimentum, nisi lacinia facilisis luctus, mauris ex euismod felis, a pharetra mi tellus vitae felis. In efficitur nisl vel velit viverra, quis semper nisl semper. Nullam libero purus, dignissim vitae hendrerit id, egestas et urna. Integer tellus justo, egestas eu libero at, mollis vehicula arcu. Mauris non varius nibh. In euismod ex vitae aliquam auctor. Mauris sed massa nibh. In hac habitasse platea dictumst. Sed ornare sagittis est, ac dictum nisl consequat porta. Mauris nec sapien et quam auctor tempus non sed justo. Aliquam vehicula, massa a sodales tempor, ipsum ligula consectetur velit, id interdum nulla lorem eu enim. Duis aliquam, ipsum ac vulputate tincidunt, elit nulla porta arcu, sed dapibus ante dolor pulvinar odio. Donec ligula sem, dapibus vel nunc quis, feugiat bibendum felis. Sed pellentesque nulla nec erat vestibulum sodales. Sed malesuada turpis vel bibendum varius. Phasellus sagittis tristique risus eu faucibus.
Curabitur molestie et metus vitae pulvinar. Integer dignissim eros nec metus laoreet, eget convallis dui tincidunt. Nullam finibus ex nec dapibus condimentum. Nam et convallis arcu, vitae auctor nisi. Aenean vel maximus tellus. Praesent placerat sapien eget orci egestas, nec pulvinar erat gravida. Etiam finibus massa ac odio porttitor imperdiet. Mauris facilisis sapien sed dui efficitur iaculis. Proin accumsan vitae est quis iaculis. Ut in convallis eros. Nulla sed consequat magna.
`
export const LOREM_TITLE = `Lorem ipsum dolor sit amet consectetur adipiscing elit`
export const CUT_OFF_LOREM_MIN = 300
export const CUT_OFF_LOREM_MAX = 1500
export const POSTS_TO_LOAD = 10
export const MAX_POSTS = 30
export const MIN_POSTS_FETCH_DELAY = 100
export const MAX_POSTS_FETCH_DELAY = 500
export const MIN_POST_RATING = 50
export const MAX_POST_RATING = 100
